title: Office of Significant Investments Review
url: https://www.osir.gov.sg
favicon: /images/logo_2.png
colors:
  primary-color: "#e68541"
  secondary-color: "#766a62"
  media-colors:
    - title: media-color-one
      color: "#ffffff"
    - title: media-color-two
      color: "#fbd030"
    - title: media-color-three
      color: "#fcb62c"
    - title: media-color-four
      color: "#ea9e52"
    - title: media-color-five
      color: "#ffffff"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d1f3dspk57jh62.amplifyapp.com
prod: https://master.d1o5tpl6mbztbg.amplifyapp.com
facebook-pixel: ""
shareicon: /images/logo_1.jpg
is_government: true
google_analytics_ga4: ""
linkedin-insights: ""
